sudo : required

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

language : generic

compiler : gcc

install:
  - cd ..
  - user_=$USER
  - chmod +x install.sh
  - sudo bash install.sh "/home/$user_"

script:
  - catkin_make krssg_ssl_msgs
  - catkin_make

notifications:
    email: false
