# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        # MainWindow.resize(1226, 653)
        MainWindow.resize(1226, 753)
        # MainWindow.showFullScreen()
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        
        ############################################
        ############################################
        ############################################
        ############################################
        # Edit This
        self.GoToBallFsm = QtGui.QPushButton(self.centralwidget)
        # self.GoToBallFsm.setGeometry(QtCore.QRect(920, 190, 121, 27))
        # self.GoToBallFsm.setObjectName(_fromUtf8("GoToBallFsm"))
        self.GoInTriangle = QtGui.QPushButton(self.centralwidget)
        # self.GoInTriangle.setGeometry(QtCore.QRect(790, 160, 99, 27))
        # self.GoInTriangle.setObjectName(_fromUtf8("GoInTriangle"))
        self.GoToBall = QtGui.QPushButton(self.centralwidget)
        # self.GoToBall.setGeometry(QtCore.QRect(920, 80, 99, 27))
        # self.GoToBall.setObjectName(_fromUtf8("GoToBall"))
        self.textBotId = QtGui.QLineEdit(self.centralwidget)
        # self.textBotId.setGeometry(QtCore.QRect(790, 80, 113, 27))
        # self.textBotId.setObjectName(_fromUtf8("textBotId"))
        self.bot_id = QtGui.QLabel(self.centralwidget)
        # self.bot_id.setGeometry(QtCore.QRect(740, 90, 41, 17))
        # self.bot_id.setObjectName(_fromUtf8("bot_id"))
        


        

        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.graphicsView.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 0);\n"
"background-color: rgb(0, 85, 0);"))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.planner_name = QtGui.QLabel(self.centralwidget)
        self.planner_name.setGeometry(QtCore.QRect(740,30,150,20))
        self.planner_name.setObjectName(_fromUtf8("planner"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(900, 30, 150, 30))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        
        # Position
        # Position Text
        self.position_type = QtGui.QLabel(self.centralwidget)
        self.position_type.setGeometry(QtCore.QRect(740,70,150,20))
        self.position_type.setObjectName(_fromUtf8("position"))
        # Position DropBox
        self.positionDropUp = QtGui.QComboBox(self.centralwidget)
        self.positionDropUp.setGeometry(QtCore.QRect(900, 70, 150, 30))
        self.positionDropUp.setObjectName(_fromUtf8("positionDropup"))
        self.positionDropUp.addItem(_fromUtf8(""))
        self.positionDropUp.addItem(_fromUtf8(""))
        # Reset Button
        self.ResetButton = QtGui.QPushButton(self.centralwidget)
        self.ResetButton.setGeometry(QtCore.QRect(1050, 110, 120, 30))
        self.ResetButton.setObjectName(_fromUtf8("Reset Position"))

        # Configure Play
        self.configure_play = QtGui.QLabel(self.centralwidget)
        self.configure_play.setGeometry(QtCore.QRect(740,130,150,20))
        self.configure_play.setObjectName(_fromUtf8("play_text"))
        # Select Team
        self.select_team = QtGui.QLabel(self.centralwidget)
        self.select_team.setGeometry(QtCore.QRect(740,150,150,20))
        self.select_team.setObjectName(_fromUtf8("select_team"))        
        # Radio Buttons
        self.team_drop_up = QtGui.QComboBox(self.centralwidget)
        self.team_drop_up.setGeometry(QtCore.QRect(900, 150, 150, 30))
        self.team_drop_up.setObjectName(_fromUtf8("team_drop_up"))
        self.team_drop_up.addItem(_fromUtf8(""))
        self.team_drop_up.addItem(_fromUtf8(""))
        # self.YellowTeam = QtGui.QRadioButton(self.centralwidget)
        # self.YellowTeam.setGeometry(QtCore.QRect(800, 200, 120, 30))
        # self.YellowTeam.setObjectName(_fromUtf8("yellow_team"))        
        # self.BlueTeam = QtGui.QRadioButton(self.centralwidget)
        # self.BlueTeam.setGeometry(QtCore.QRect(950, 200, 120, 30))
        # self.BlueTeam.setObjectName(_fromUtf8("blue_team"))

        # Select Goalie
        self.select_goalie = QtGui.QLabel(self.centralwidget)
        self.select_goalie.setGeometry(QtCore.QRect(740,190,150,20))
        self.select_goalie.setObjectName(_fromUtf8("select_goalie"))        
        # Dropup List
        self.goalie_drop_up = QtGui.QComboBox(self.centralwidget)
        self.goalie_drop_up.setGeometry(QtCore.QRect(900, 190, 150, 30))
        self.goalie_drop_up.setObjectName(_fromUtf8("goalie_drop_up"))
        self.goalie_drop_up.addItem(_fromUtf8(""))
        self.goalie_drop_up.addItem(_fromUtf8(""))
        self.goalie_drop_up.addItem(_fromUtf8(""))
        self.goalie_drop_up.addItem(_fromUtf8(""))
        self.goalie_drop_up.addItem(_fromUtf8(""))
        self.goalie_drop_up.addItem(_fromUtf8(""))
        # self.bot_0 = QtGui.QRadioButton(self.centralwidget)
        # self.bot_0.setGeometry(QtCore.QRect(750, 280, 40, 30))
        # self.bot_0.setObjectName(_fromUtf8("bot_0"))        
        # self.bot_1 = QtGui.QRadioButton(self.centralwidget)
        # self.bot_1.setGeometry(QtCore.QRect(800, 280, 40, 30))
        # self.bot_1.setObjectName(_fromUtf8("bot_1"))
        # self.bot_2 = QtGui.QRadioButton(self.centralwidget)
        # self.bot_2.setGeometry(QtCore.QRect(850, 280, 40, 30))
        # self.bot_2.setObjectName(_fromUtf8("bot_0"))        
        # self.bot_3 = QtGui.QRadioButton(self.centralwidget)
        # self.bot_3.setGeometry(QtCore.QRect(900, 280, 40, 30))
        # self.bot_3.setObjectName(_fromUtf8("bot_1"))
        # self.bot_4 = QtGui.QRadioButton(self.centralwidget)
        # self.bot_4.setGeometry(QtCore.QRect(950, 280, 40, 30))
        # self.bot_4.setObjectName(_fromUtf8("bot_0"))        
        # self.bot_5 = QtGui.QRadioButton(self.centralwidget)
        # self.bot_5.setGeometry(QtCore.QRect(1000, 280, 40, 30))
        # self.bot_5.setObjectName(_fromUtf8("bot_1"))

        # Text
        self.play_text = QtGui.QLabel(self.centralwidget)
        self.play_text.setGeometry(QtCore.QRect(740,230,150,20))
        self.play_text.setObjectName(_fromUtf8("play_text"))
        # Radio Buttons
        self.OffensivePlay = QtGui.QRadioButton(self.centralwidget)
        self.OffensivePlay.setGeometry(QtCore.QRect(900, 230, 120, 30))
        self.OffensivePlay.setObjectName(_fromUtf8("Offensive"))        
        self.DefensivePlay = QtGui.QRadioButton(self.centralwidget)
        self.DefensivePlay.setGeometry(QtCore.QRect(1000, 230, 120, 30))
        self.DefensivePlay.setObjectName(_fromUtf8("Defense"))        
        self.StallPlay = QtGui.QRadioButton(self.centralwidget)
        self.StallPlay.setGeometry(QtCore.QRect(1100, 230, 120, 30))
        self.StallPlay.setObjectName(_fromUtf8("Stall"))
        # Start Play Button
        self.StartPlay = QtGui.QPushButton(self.centralwidget)
        self.StartPlay.setGeometry(QtCore.QRect(1050, 260, 120, 30))
        self.StartPlay.setObjectName(_fromUtf8("Reset Position"))


        # Play Information
        self.play_information = QtGui.QLabel(self.centralwidget)
        self.play_information.setGeometry(QtCore.QRect(10,500,150,20))
        self.play_information.setObjectName(_fromUtf8("play_information"))
        
        self.Score = QtGui.QLabel(self.centralwidget)
        self.Score.setGeometry(QtCore.QRect(10,550,150,20))
        self.Score.setObjectName(_fromUtf8("Score"))
        self.RedCard = QtGui.QLabel(self.centralwidget)
        self.RedCard.setGeometry(QtCore.QRect(10,580,150,20))
        self.RedCard.setObjectName(_fromUtf8("RedCard")) 
        self.YellowCard = QtGui.QLabel(self.centralwidget)
        self.YellowCard.setGeometry(QtCore.QRect(10,610,150,20))
        self.YellowCard.setObjectName(_fromUtf8("YellowCard"))
        self.TimeOutLeft = QtGui.QLabel(self.centralwidget)
        self.TimeOutLeft.setGeometry(QtCore.QRect(10,640,150,20))
        self.TimeOutLeft.setObjectName(_fromUtf8("TimeOutLeft"))



        self.homeTeamName = QtGui.QLabel(self.centralwidget)
        self.homeTeamName.setGeometry(QtCore.QRect(170,520,150,20))
        self.homeTeamName.setObjectName(_fromUtf8("homeTeamName"))
        self.homeTeamScore = QtGui.QLabel(self.centralwidget)
        self.homeTeamScore.setGeometry(QtCore.QRect(200,550,150,20))
        self.homeTeamScore.setObjectName(_fromUtf8("homeTeamScore"))
        self.homeTeamRedCard = QtGui.QLabel(self.centralwidget)
        self.homeTeamRedCard.setGeometry(QtCore.QRect(200,580,150,20))
        self.homeTeamRedCard.setObjectName(_fromUtf8("homeTeamRedCard")) 
        self.homeTeamYellowCard = QtGui.QLabel(self.centralwidget)
        self.homeTeamYellowCard.setGeometry(QtCore.QRect(200,610,150,20))
        self.homeTeamYellowCard.setObjectName(_fromUtf8("homeTeamYellowCard"))
        self.homeTeamTimeOutLeft = QtGui.QLabel(self.centralwidget)
        self.homeTeamTimeOutLeft.setGeometry(QtCore.QRect(200,640,150,20))
        self.homeTeamTimeOutLeft.setObjectName(_fromUtf8("homeTeamTimeOutLeft"))
         
        self.oppTeamName = QtGui.QLabel(self.centralwidget)
        self.oppTeamName.setGeometry(QtCore.QRect(300,520,150,20))
        self.oppTeamName.setObjectName(_fromUtf8("oppTeamName"))
        self.oppTeamScore = QtGui.QLabel(self.centralwidget)
        self.oppTeamScore.setGeometry(QtCore.QRect(330,550,150,20))
        self.oppTeamScore.setObjectName(_fromUtf8("oppTeamScore"))
        self.oppTeamRedCard = QtGui.QLabel(self.centralwidget)
        self.oppTeamRedCard.setGeometry(QtCore.QRect(330,580,150,20))
        self.oppTeamRedCard.setObjectName(_fromUtf8("oppTeamRedCard")) 
        self.oppTeamYellowCard = QtGui.QLabel(self.centralwidget)
        self.oppTeamYellowCard.setGeometry(QtCore.QRect(330,610,150,20))
        self.oppTeamYellowCard.setObjectName(_fromUtf8("oppTeamYellowCard"))
        self.oppTeamTimeOutLeft = QtGui.QLabel(self.centralwidget)
        self.oppTeamTimeOutLeft.setGeometry(QtCore.QRect(330,640,150,20))
        self.oppTeamTimeOutLeft.setObjectName(_fromUtf8("oppTeamTimeOutLeft"))
        

        






        self.Refree_Command = QtGui.QLabel(self.centralwidget)
        self.Refree_Command.setGeometry(QtCore.QRect(460,520,150,20))
        self.Refree_Command.setObjectName(_fromUtf8("Refree_Command"))
        self.time_left = QtGui.QLabel(self.centralwidget)
        self.time_left.setGeometry(QtCore.QRect(460,550,150,20))
        self.time_left.setObjectName(_fromUtf8("time_left"))
        self.Opp_Bots = QtGui.QLabel(self.centralwidget)
        self.Opp_Bots.setGeometry(QtCore.QRect(460,580,150,20))
        self.Opp_Bots.setObjectName(_fromUtf8("Opp_Bots")) 
        self.Opp_Goalie = QtGui.QLabel(self.centralwidget)
        self.Opp_Goalie.setGeometry(QtCore.QRect(460,610,150,20))
        self.Opp_Goalie.setObjectName(_fromUtf8("Opp_Goalie"))
        self.Opp_Color = QtGui.QLabel(self.centralwidget)
        self.Opp_Color.setGeometry(QtCore.QRect(460,640,150,20))
        self.Opp_Color.setObjectName(_fromUtf8("Opp_Color"))
        

        self.Refree_Command_value = QtGui.QLabel(self.centralwidget)
        self.Refree_Command_value.setGeometry(QtCore.QRect(600,520,150,20))
        self.Refree_Command_value.setObjectName(_fromUtf8("Refree_Command_value"))
        self.time_left_value = QtGui.QLabel(self.centralwidget)
        self.time_left_value.setGeometry(QtCore.QRect(600,550,150,20))
        self.time_left_value.setObjectName(_fromUtf8("time_left_value"))
        self.Opp_Bots_value = QtGui.QLabel(self.centralwidget)
        self.Opp_Bots_value.setGeometry(QtCore.QRect(600,580,150,20))
        self.Opp_Bots_value.setObjectName(_fromUtf8("Opp_Bots_value")) 
        self.Opp_Goalie_value = QtGui.QLabel(self.centralwidget)
        self.Opp_Goalie_value.setGeometry(QtCore.QRect(600,610,150,20))
        self.Opp_Goalie_value.setObjectName(_fromUtf8("Opp_Goalie_value"))
        self.Opp_Color_value = QtGui.QLabel(self.centralwidget)
        self.Opp_Color_value.setGeometry(QtCore.QRect(600,640,150,20))
        self.Opp_Color_value.setObjectName(_fromUtf8("Opp_Color_value"))
        
        self.current_play = QtGui.QLabel(self.centralwidget)
        self.current_play.setGeometry(QtCore.QRect(900,520,150,20))
        self.current_play.setObjectName(_fromUtf8("current_play"))
        self.bot_0_status = QtGui.QLabel(self.centralwidget)
        self.bot_0_status.setGeometry(QtCore.QRect(780,550,150,20))
        self.bot_0_status.setObjectName(_fromUtf8("bot_0_status"))
        self.bot_1_status = QtGui.QLabel(self.centralwidget)
        self.bot_1_status.setGeometry(QtCore.QRect(930,550,150,20))
        self.bot_1_status.setObjectName(_fromUtf8("bot_1_status"))
        self.bot_2_status = QtGui.QLabel(self.centralwidget)
        self.bot_2_status.setGeometry(QtCore.QRect(1080,550,150,20))
        self.bot_2_status.setObjectName(_fromUtf8("bot_2_status"))
        self.bot_3_status = QtGui.QLabel(self.centralwidget)
        self.bot_3_status.setGeometry(QtCore.QRect(780,610,150,20))
        self.bot_3_status.setObjectName(_fromUtf8("bot_3_status"))
        self.bot_4_status = QtGui.QLabel(self.centralwidget)
        self.bot_4_status.setGeometry(QtCore.QRect(930,610,150,20))
        self.bot_4_status.setObjectName(_fromUtf8("bot_4_status"))
        self.bot_5_status = QtGui.QLabel(self.centralwidget)
        self.bot_5_status.setGeometry(QtCore.QRect(1080,610,150,20))
        self.bot_5_status.setObjectName(_fromUtf8("bot_5_status"))
   

        self.current_play_value = QtGui.QLabel(self.centralwidget)
        self.current_play_value.setGeometry(QtCore.QRect(950,520,150,20))
        self.current_play_value.setObjectName(_fromUtf8("current_play_value"))
        self.bot_0_status_value = QtGui.QLabel(self.centralwidget)
        self.bot_0_status_value.setGeometry(QtCore.QRect(750,580,150,20))
        self.bot_0_status_value.setObjectName(_fromUtf8("bot_0_status_value"))
        self.bot_1_status_value = QtGui.QLabel(self.centralwidget)
        self.bot_1_status_value.setGeometry(QtCore.QRect(900,580,150,20))
        self.bot_1_status_value.setObjectName(_fromUtf8("bot_1_status_value"))
        self.bot_2_status_value = QtGui.QLabel(self.centralwidget)
        self.bot_2_status_value.setGeometry(QtCore.QRect(1050,580,150,20))
        self.bot_2_status_value.setObjectName(_fromUtf8("bot_2_status_value"))
        self.bot_3_status_value = QtGui.QLabel(self.centralwidget)
        self.bot_3_status_value.setGeometry(QtCore.QRect(750,640,150,20))
        self.bot_3_status_value.setObjectName(_fromUtf8("bot_3_status_value"))
        self.bot_4_status_value = QtGui.QLabel(self.centralwidget)
        self.bot_4_status_value.setGeometry(QtCore.QRect(900,640,150,20))
        self.bot_4_status_value.setObjectName(_fromUtf8("bot_4_status_value"))
        self.bot_5_status_value = QtGui.QLabel(self.centralwidget)
        self.bot_5_status_value.setGeometry(QtCore.QRect(1050,640,150,20))
        self.bot_5_status_value.setObjectName(_fromUtf8("bot_5_status_value"))        


         # Testing Options
         # Text
        self.test_text = QtGui.QLabel(self.centralwidget)
        self.test_text.setGeometry(QtCore.QRect(740,290,150,20))
        self.test_text.setObjectName(_fromUtf8("test_text"))
        # Dropup list for each bot
        self.for_bot_0 = QtGui.QLabel(self.centralwidget)
        self.for_bot_0.setGeometry(QtCore.QRect(740,325,50,20))
        self.for_bot_0.setObjectName(_fromUtf8("for_bot_0"))
        self.bot_0_drop_up = QtGui.QComboBox(self.centralwidget)
        self.bot_0_drop_up.setGeometry(QtCore.QRect(790, 320, 100, 30))
        self.bot_0_drop_up.setObjectName(_fromUtf8("bot_0_drop_up"))
        self.bot_0_drop_up.addItem(_fromUtf8(""))
        self.bot_0_drop_up.addItem(_fromUtf8(""))
        self.for_bot_1 = QtGui.QLabel(self.centralwidget)
        self.for_bot_1.setGeometry(QtCore.QRect(895,325,100,20))
        self.for_bot_1.setObjectName(_fromUtf8("for_bot_1"))
        self.bot_1_drop_up = QtGui.QComboBox(self.centralwidget)
        self.bot_1_drop_up.setGeometry(QtCore.QRect(945, 320, 100, 30))
        self.bot_1_drop_up.setObjectName(_fromUtf8("bot_1_drop_up"))
        self.bot_1_drop_up.addItem(_fromUtf8(""))
        self.bot_1_drop_up.addItem(_fromUtf8(""))
        self.for_bot_2 = QtGui.QLabel(self.centralwidget)
        self.for_bot_2.setGeometry(QtCore.QRect(1050,325,100,20))
        self.for_bot_2.setObjectName(_fromUtf8("for_bot_2"))
        self.bot_2_drop_up = QtGui.QComboBox(self.centralwidget)
        self.bot_2_drop_up.setGeometry(QtCore.QRect(1095, 320, 100, 30))
        self.bot_2_drop_up.setObjectName(_fromUtf8("bot_2_drop_up"))
        self.bot_2_drop_up.addItem(_fromUtf8(""))
        self.bot_2_drop_up.addItem(_fromUtf8(""))
        self.for_bot_3 = QtGui.QLabel(self.centralwidget)
        self.for_bot_3.setGeometry(QtCore.QRect(740,355,50,20))
        self.for_bot_3.setObjectName(_fromUtf8("for_bot_3"))
        self.bot_3_drop_up = QtGui.QComboBox(self.centralwidget)
        self.bot_3_drop_up.setGeometry(QtCore.QRect(790, 350, 100, 30))
        self.bot_3_drop_up.setObjectName(_fromUtf8("bot_3_drop_up"))
        self.bot_3_drop_up.addItem(_fromUtf8(""))
        self.bot_3_drop_up.addItem(_fromUtf8(""))
        self.for_bot_4 = QtGui.QLabel(self.centralwidget)
        self.for_bot_4.setGeometry(QtCore.QRect(895,355,100,20))
        self.for_bot_4.setObjectName(_fromUtf8("for_bot_4"))
        self.bot_4_drop_up = QtGui.QComboBox(self.centralwidget)
        self.bot_4_drop_up.setGeometry(QtCore.QRect(945, 350, 100, 30))
        self.bot_4_drop_up.setObjectName(_fromUtf8("bot_4_drop_up"))
        self.bot_4_drop_up.addItem(_fromUtf8(""))
        self.bot_4_drop_up.addItem(_fromUtf8(""))
        self.for_bot_5 = QtGui.QLabel(self.centralwidget)
        self.for_bot_5.setGeometry(QtCore.QRect(1050,355,100,20))
        self.for_bot_5.setObjectName(_fromUtf8("for_bot_5"))
        self.bot_5_drop_up = QtGui.QComboBox(self.centralwidget)
        self.bot_5_drop_up.setGeometry(QtCore.QRect(1095, 350, 100, 30))
        self.bot_5_drop_up.setObjectName(_fromUtf8("bot_5_drop_up"))
        self.bot_5_drop_up.addItem(_fromUtf8(""))
        self.bot_5_drop_up.addItem(_fromUtf8(""))
        self.TestButton = QtGui.QPushButton(self.centralwidget)
        self.TestButton.setGeometry(QtCore.QRect(1050, 400, 120, 30))
        self.TestButton.setObjectName(_fromUtf8("Test"))
        

        self.StartButton = QtGui.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(800, 460, 140, 40))
        self.StartButton.setObjectName(_fromUtf8("Stop"))        

        self.StopButton = QtGui.QPushButton(self.centralwidget)
        self.StopButton.setGeometry(QtCore.QRect(1000, 450, 160, 60))
        self.StopButton.setObjectName(_fromUtf8("Stop"))



        # self.table = QtGui.QTableWidget(self.centralwidget)
        # self.table.setGeometry(QtCore.QRect(0,500,250,180))
        # self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.table.setColumnCount(3)
        # self.table.setRowCount(5)
        # self.table.setRowHeight(0,30)
        # self.table.setRowHeight(1,35)
        # self.table.setRowHeight(2,35)
        # self.table.setRowHeight(3,35)
        # self.table.setRowHeight(4,35)
        # self.table.setColumnWidth(0,90)
        # self.table.setColumnWidth(1,75)
        # self.table.setColumnWidth(2,85)
        # # set label
        # self.table.setShowGrid(False)
        # self.table.verticalHeader().setVisible(False)
        # self.table.horizontalHeader().setVisible(False)
        # self.table.setItem(0,1, QtGui.QTableWidgetItem("KgpKubs"))
        # self.table.setItem(0,2, QtGui.QTableWidgetItem("Opp Team"))
        # self.table.setItem(1,0, QtGui.QTableWidgetItem("Score"))
        # self.table.setItem(1,1, QtGui.QTableWidgetItem("0"))
        # self.table.setItem(1,2, QtGui.QTableWidgetItem("0"))
        # self.table.setItem(2,0, QtGui.QTableWidgetItem("Red Cards"))
        # self.table.setItem(2,1, QtGui.QTableWidgetItem("0"))
        # self.table.setItem(2,2, QtGui.QTableWidgetItem("0"))
        # self.table.setItem(3,0, QtGui.QTableWidgetItem("Yellow Cards"))
        # self.table.setItem(3,1, QtGui.QTableWidgetItem("0"))
        # self.table.setItem(3,2, QtGui.QTableWidgetItem("0"))
        # self.table.setItem(4,0, QtGui.QTableWidgetItem("TimeOut Left"))
        # self.table.setItem(4,1, QtGui.QTableWidgetItem("0"))
        # self.table.setItem(4,2, QtGui.QTableWidgetItem("0"))




        # self.botAvailable = QtGui.QTableWidget(self.centralwidget)
        # self.botAvailable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.botAvailable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.botAvailable.setGeometry(QtCore.QRect(400,500,750,180))
        # self.botAvailable.setRowCount(3)
        # self.botAvailable.setColumnCount(7)
        # self.botAvailable.setRowHeight(0,30)
        # self.botAvailable.setRowHeight(1,65)
        # self.botAvailable.setRowHeight(2,75)
        # self.botAvailable.setShowGrid(False)
        # self.botAvailable.verticalHeader().setVisible(False)
        # self.botAvailable.horizontalHeader().setVisible(False)
        # # self.botAvailable.setItem(0,0, QtGui.QTableWidgetItem("0"))
        # self.botAvailable.setItem(0,1, QtGui.QTableWidgetItem("BotId 0"))
        # self.botAvailable.setItem(0,2, QtGui.QTableWidgetItem("BotId 1"))
        # self.botAvailable.setItem(0,3, QtGui.QTableWidgetItem("BotId 2"))
        # self.botAvailable.setItem(0,4, QtGui.QTableWidgetItem("BotId 3"))
        # self.botAvailable.setItem(0,5, QtGui.QTableWidgetItem("BotId 4"))
        # self.botAvailable.setItem(0,6, QtGui.QTableWidgetItem("BotId 5"))        
        # self.botAvailable.setItem(1,0, QtGui.QTableWidgetItem("KgpKubs"))
        # self.botAvailable.setItem(1,1, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(1,2, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(1,3, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(1,4, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(1,5, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(1,6, QtGui.QTableWidgetItem("Available"))        
        # self.botAvailable.setItem(2,0, QtGui.QTableWidgetItem("Opp Team"))
        # self.botAvailable.setItem(2,1, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(2,2, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(2,3, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(2,4, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(2,5, QtGui.QTableWidgetItem("Available"))
        # self.botAvailable.setItem(2,6, QtGui.QTableWidgetItem("Available"))




        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 25))
        self.menubar.setNativeMenuBar(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDIFFERENT_RRT = QtGui.QMenu(self.menubar)
        self.menuDIFFERENT_RRT.setObjectName(_fromUtf8("menuDIFFERENT_RRT"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionRRT_CONNECT = QtGui.QAction(MainWindow)
        self.actionRRT_CONNECT.setObjectName(_fromUtf8("actionRRT_CONNECT"))
        self.actionRRTStar = QtGui.QAction(MainWindow)
        self.actionRRTStar.setObjectName(_fromUtf8("actionRRTStar"))
        self.actionRRT = QtGui.QAction(MainWindow)
        self.actionRRT.setObjectName(_fromUtf8("actionRRT"))
        self.menubar.addAction(self.menuDIFFERENT_RRT.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "KgpKubs-SSL", None))
        self.GoToBall.setText(_translate("MainWindow", "GoToBall", None))
        self.bot_id.setText(_translate("MainWindow", "BotId", None))
        

        self.planner_name.setText(_translate("MainWindow", "Planner", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "PRM", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "RRT", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "RRTConnect", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "RRTStar", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "LBTRRT", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "LazyRRT", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "TRRT", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "pRRT", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "EST", None))
        
        self.position_type.setText(_translate("MainWindow", "Set Initial Position", None))
        self.positionDropUp.setItemText(0, _translate("MainWindow", "Position 1", None))
        self.positionDropUp.setItemText(1, _translate("MainWindow", "Position 2", None))
        self.ResetButton.setText(_translate("MainWindow", "Reset Position", None))
        # Plays
        self.configure_play.setText(_translate("MainWindow"," Configure Play", None))
        self.select_team.setText(_translate("MainWindow"," Select Team", None))
        self.team_drop_up.setItemText(0, _translate("MainWindow", "Yellow", None))
        self.team_drop_up.setItemText(1, _translate("MainWindow", "Blue", None))
        self.goalie_drop_up.setItemText(0, _translate("MainWindow", "0", None))
        self.goalie_drop_up.setItemText(1, _translate("MainWindow", "1", None))
        self.goalie_drop_up.setItemText(2, _translate("MainWindow", "2", None))
        self.goalie_drop_up.setItemText(3, _translate("MainWindow", "3", None))
        self.goalie_drop_up.setItemText(4, _translate("MainWindow", "4", None))
        self.goalie_drop_up.setItemText(5, _translate("MainWindow", "5", None))
        self.select_goalie.setText(_translate("MainWindow"," Select Goalie", None))
        self.play_text.setText(_translate("MainWindow"," Select Play", None))
        self.OffensivePlay.setText(_translate("MainWindow","Offensive", None))
        self.DefensivePlay.setText(_translate("MainWindow","Defensive", None))
        self.StallPlay.setText(_translate("MainWindow","Stall", None))
        self.StartPlay.setText(_translate("MainWindow","Start Play", None))
        
        self.test_text.setText(_translate("MainWindow","Testing", None))
        self.for_bot_0.setText(_translate("MainWindow","Bot 0", None))
        self.bot_0_drop_up.setItemText(0, _translate("MainWindow", "GoToBall", None))
        self.bot_0_drop_up.setItemText(1, _translate("MainWindow", "GoToPoint", None))
        self.for_bot_1.setText(_translate("MainWindow","Bot 1", None))
        self.bot_1_drop_up.setItemText(0, _translate("MainWindow", "GoToBall", None))
        self.bot_1_drop_up.setItemText(1, _translate("MainWindow", "GoToPoint", None))
        self.for_bot_2.setText(_translate("MainWindow","Bot 2", None))
        self.bot_2_drop_up.setItemText(0, _translate("MainWindow", "GoToBall", None))
        self.bot_2_drop_up.setItemText(1, _translate("MainWindow", "GoToPoint", None))
        self.for_bot_3.setText(_translate("MainWindow","Bot 3", None))
        self.bot_3_drop_up.setItemText(0, _translate("MainWindow", "GoToBall", None))
        self.bot_3_drop_up.setItemText(1, _translate("MainWindow", "GoToPoint", None))
        self.for_bot_4.setText(_translate("MainWindow","Bot 4", None))
        self.bot_4_drop_up.setItemText(0, _translate("MainWindow", "GoToBall", None))
        self.bot_4_drop_up.setItemText(1, _translate("MainWindow", "GoToPoint", None))
        self.for_bot_5.setText(_translate("MainWindow","Bot 5", None))
        self.bot_5_drop_up.setItemText(0, _translate("MainWindow", "GoToBall", None))
        self.bot_5_drop_up.setItemText(1, _translate("MainWindow", "GoToPoint", None))
     
        # Play Information
        self.play_information.setText(_translate("MainWindow","Play Infromation", None))
        self.Refree_Command.setText(_translate("MainWindow","Refree Command", None))
        self.time_left.setText(_translate("MainWindow","Time Left", None))
        self.Opp_Bots.setText(_translate("MainWindow","Opp robots", None))
        self.Opp_Goalie.setText(_translate("MainWindow","Opp Goalie", None))
        self.Opp_Color.setText(_translate("MainWindow","Opp Color", None))
        self.Refree_Command_value.setText(_translate("MainWindow","Stop", None))
        self.time_left_value.setText(_translate("MainWindow","0.00s", None))
        self.Opp_Bots_value.setText(_translate("MainWindow","6", None))
        self.Opp_Goalie_value.setText(_translate("MainWindow","5", None))
        self.Opp_Color_value.setText(_translate("MainWindow","Blue", None))
        self.current_play.setText(_translate("MainWindow","Play", None))
        self.bot_0_status.setText(_translate("MainWindow","Bot 0", None))
        self.bot_1_status.setText(_translate("MainWindow","Bot 1", None))
        self.bot_2_status.setText(_translate("MainWindow","Bot 2", None))
        self.bot_3_status.setText(_translate("MainWindow","Bot 3", None))
        self.bot_4_status.setText(_translate("MainWindow","Bot 4", None))
        self.bot_5_status.setText(_translate("MainWindow","Bot 5", None))

        self.current_play_value.setText(_translate("MainWindow","Stall || 0.00", None))
        self.bot_0_status_value.setText(_translate("MainWindow","Attacker || 0.00", None))
        self.bot_1_status_value.setText(_translate("MainWindow","Attacker || 0.00", None))
        self.bot_2_status_value.setText(_translate("MainWindow","Attacker || 0.00", None))
        self.bot_3_status_value.setText(_translate("MainWindow","Attacker || 0.00", None))
        self.bot_4_status_value.setText(_translate("MainWindow","Attacker || 0.00", None))
        self.bot_5_status_value.setText(_translate("MainWindow","Attacker || 0.00", None))
        
        self.TestButton.setText(_translate("MainWindow","Start Test", None))
        self.StartButton.setText(_translate("MainWindow","Start Play Selector", None))
        
        self.StopButton.setText(_translate("MainWindow","Stop", None))
        
        self.Score.setText(_translate("MainWindow","Score", None))
        self.RedCard.setText(_translate("MainWindow","Red Cards Given", None))
        self.YellowCard.setText(_translate("MainWindow","Yellow Cards Given", None))
        self.TimeOutLeft.setText(_translate("MainWindow","Time Outs Left", None))
        self.homeTeamName.setText(_translate("MainWindow","KgpKubs", None))
        self.homeTeamScore.setText(_translate("MainWindow","0", None))
        self.homeTeamRedCard.setText(_translate("MainWindow","0", None))
        self.homeTeamYellowCard.setText(_translate("MainWindow","0", None))
        self.homeTeamTimeOutLeft.setText(_translate("MainWindow","0", None))
        self.oppTeamName.setText(_translate("MainWindow","Opp Team", None))
        self.oppTeamScore.setText(_translate("MainWindow","0", None))
        self.oppTeamRedCard.setText(_translate("MainWindow","0", None))
        self.oppTeamYellowCard.setText(_translate("MainWindow","0", None))
        self.oppTeamTimeOutLeft.setText(_translate("MainWindow","0", None))




        self.GoToBallFsm.setText(_translate("MainWindow", "", None))
        self.GoInTriangle.setText(_translate("MainWindow", "", None))
        self.menuDIFFERENT_RRT.setTitle(_translate("MainWindow", "GUI", None))
        self.actionRRT_CONNECT.setText(_translate("MainWindow", "RRT_CONNECT", None))
        self.actionRRTStar.setText(_translate("MainWindow", "RRT_STAR", None))
        self.actionRRT.setText(_translate("MainWindow", "RRT", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

